import { PageCard } from "@/components/layout/page-card";

export default async function GroupNoticesPage({
  params,
}: {
  params: Promise<{ token: string }>;
}) {
  const { token } = await params;

  return (
    <PageCard
      eyebrow={`Notices ${token}`}
      title="Group notice board"
      description="Members will see all public notices for the group here, including system notices generated by admin actions."
    />
  );
}
